# Generated by Django 3.1.5 on 2021-01-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210112_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_pud',
            new_name='date_pub',
        ),
    ]
